# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f41b788069d37dc10e2424ade92b9ebf19e5aa9311f14b7fe13b6b460fe2e75da5e865c539ed2a40b18b1ddde4fb54bd77e916e487cb262712334c942ed9bb0b

test:
  secret_key_base: 2cab655673536ce6e3cb5be1bceebb8e17492dff785e0cb8cf09b7248176b2409661ff068f03c261ef39a4d530e121dc91068130cd080a45bf4fce738f8f56ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
